### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by cdunworth** [asbjornenge/websocketd.js#1]
should   conn.proc.kill('SIGHUP')   not be  conn.proc.kill(proc.pid,'SIGHUP')   ?

**Comment by asbjornenge** [comment]
Not according to http://nodejs.org/api/child_process.html#child_process_child_kill_signal ... ?
conn.proc is a ChildProcess returned by spawn.

**Comment by cdunworth** [comment]
my confusion, I was looking at
http://nodejs.org/api/process.html#process_process_kill_pid_signal
my real problem is SIGHUP does not seem to have any effect on my spawned
process

Neat piece of code, Thank you.

**Comment by asbjornenge** [comment]
@cdunworth :+1: 

You could try to verify that the correct signal is sent doing something like this:

```
conn.proc.on('close', function (code, signal) {
    console.log('child process terminated due to receipt of signal '+signal);
});

// send SIGHUP to process
conn.proc.kill('SIGHUP');
```

I'll close this issue for now, but feel free to report back if you find there is a problem with the code. It might  be a platform issue or a bug in node.
